# Generated by Django 5.0.2 on 2024-03-05 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_tags_order_tags'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tags',
            new_name='Tag',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='tags',
            new_name='tag',
        ),
    ]
