# Generated by Django 5.0.2 on 2024-03-05 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_rename_tags_tag_rename_tags_order_tag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='tag',
            new_name='tags',
        ),
    ]
